spring.application.name=CloudStorage
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}

spring.session.store-type=redis
spring.session.redis.namespace=cloudstorage:sessions
spring.session.timeout=6h

server.servlet.session.timeout=12h
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=true

minio.endpoint=${MINIO_ENDPOINT}
minio.access-key=${MINIO_ROOT_USER}
minio.secret-key=${MINIO_ROOT_PASSWORD}
minio.root-bucket=${MINIO_BUCKET}

spring.servlet.multipart.max-file-size=300MB
spring.servlet.multipart.max-request-size=300MB
spring.servlet.multipart.enabled=true